main = ".open-next/worker.js"
name = "discord-userdoccers"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
