blank_issues_enabled: false
contact_links:
  - name: Contributing Guide
    url: https://github.com/discord-userdoccers/discord-userdoccers/blob/master/CONTRIBUTING.md
    about: We are a small team, and community contributions are what keep these docs alive. Consider submitting a pull request before opening an issue!
